services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - caddy_0=http://backend.dovale.online
      - caddy_0.encode=zstd gzip
      - caddy_0.handle_path=/*
      - caddy_0.handle_path.0_reverse_proxy={{upstreams 3001}}
      - caddy_0.header=-Server
      - caddy_ingress_network=coolify

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: https://backend.dovale.online/api
    restart: unless-stopped
    networks:
      - coolify
    labels:
      - caddy_0=http://lojas.dovale.online
      - caddy_0.encode=zstd gzip
      - caddy_0.handle_path=/*
      - caddy_0.handle_path.0_reverse_proxy={{upstreams 80}}
      - caddy_0.header=-Server
      - caddy_0.try_files={path} /index.html
      - caddy_ingress_network=coolify

networks:
  coolify:
    external: true
