services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.backend-http.rule=Host(`backend.dovale.online`)
      - traefik.http.routers.backend-http.entrypoints=web
      - traefik.http.routers.backend-http.service=backend-svc
      - traefik.http.services.backend-svc.loadbalancer.server.port=3001

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_URL: https://backend.dovale.online/api
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.frontend-http.rule=Host(`lojas.dovale.online`)
      - traefik.http.routers.frontend-http.entrypoints=web
      - traefik.http.routers.frontend-http.service=frontend-svc
      - traefik.http.services.frontend-svc.loadbalancer.server.port=80
